### ISSUE TITLE
adopt golang-standards/project-layout 

### ISSUE THREAD

**Issue by flokli** [numtide/go-nix#10]
Link: https://github.com/golang-standards/project-layout

**Comment by zimbatm** [comment]
So throw everything under `/internal` as it's unstable?

**Comment by flokli** [comment]
No, I think some of the code is valuable to be used in a library context, but we should come up with a consistent structure.

I logged this as an action item for now, didn't put many thoughts into *how* the structure should look like.

**Comment by flokli** [comment]
With https://github.com/numtide/go-nix/pull/23 in place, it feels like a good time. I try to tackle this in the coming days.

**Comment by zimbatm** [comment]
sounds good!
